CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS stages (id INTEGER PRIMARY KEY AUTOINCREMENT, day INTEGER NOT NULL, name TEXT NOT NULL, time TEXT NOT NULL DEFAULT '', joinable INTEGER NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS shops (id INTEGER PRIMARY KEY AUTOINCREMENT, shop_no TEXT NOT NULL DEFAULT '', name TEXT NOT NULL, sells TEXT NOT NULL DEFAULT '', sort_order INTEGER NOT NULL DEFAULT 0);
